# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta una vez al día
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: cristobalbelcor
          outputs: |
            ./dist/snake.svg

      - name: Commit snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "update snake animation"
          add: "dist/snake.svg"

